-- Migration gf_ls/002: portal tables for the web frontend (Block 3a).

CREATE TABLE public.web_account (
    account_id     integer PRIMARY KEY REFERENCES public.accounts(id),
    email          text UNIQUE,
    email_verified boolean NOT NULL DEFAULT false,
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.web_admin (
    account_id integer PRIMARY KEY REFERENCES public.accounts(id),
    granted_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.web_news (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             text NOT NULL,
    body              text NOT NULL,
    author_account_id integer REFERENCES public.accounts(id),
    published_at      timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.web_token (
    token      text PRIMARY KEY,
    account_id integer NOT NULL REFERENCES public.accounts(id),
    purpose    text NOT NULL CHECK (purpose IN ('password_reset', 'email_verify')),
    expires_at timestamptz NOT NULL,
    used_at    timestamptz
);

CREATE TABLE public.web_login_attempt (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip           text NOT NULL,
    attempted_at timestamptz NOT NULL DEFAULT now(),
    success      boolean NOT NULL
);

CREATE INDEX web_login_attempt_ip_time_idx
    ON public.web_login_attempt (ip, attempted_at);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.web_account TO gf_web;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.web_admin TO gf_web;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.web_news TO gf_web;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.web_token TO gf_web;
GRANT SELECT, INSERT, DELETE ON public.web_login_attempt TO gf_web;
